config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'home#index', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :topics
  root to: 'home#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :student, class_name: User
  scope :approved, -> { where(approved: true) }
  scope :pending_approval, -> { where(approved: [false, nil]) }
  scope :completed, -> { where.not(completed_date: nil) }
  scope :not_completed, -> { where(completed_date: nil) }

  validates :student, :title, :description, :proposed_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :trackable, :omniauthable, omniauth_providers: [:github]

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.github_name = auth.info.nickname
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def new_session_path(scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @approved_topics = Topic.approved.not_completed
    @pending_topics = Topic.pending_approval.not_completed
    @completed_topics = Topic.completed
    @headings = [:student_id, :title, :description, :proposed_date, :completed_date]
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @student = @topic.student
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.student = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.student == current_user && @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        flash[:notice] = "You can not edit a topic that isn't yours!"
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    respond_to do |format|
      if @topic.student == current_user
        @topic.destroy
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to topics_url, notice: "You can not destroy a topic that isn't yours!" }
        format.json { render json: "You can not destroy a topic that isn't yours!", status: :unprocessable_entity}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :proposed_date)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def get_student_name_for topic
    return "unknown" if topic.student.nil?
    topic.student.name
  end
end

app/views/home/index.html.haml
%h1 Welcome!
%p To sign up for a lighting talk, please login with Github and enter your topic!
%p= link_to "Sign In with Github", user_omniauth_authorize_path(provider: :github)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Lightning310"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{href: "#"} Lightning310
          .container-fluid.nav-collapse
            %ul.nav
              - if current_user
                %li= link_to "Sign Out", destroy_user_session_path
              - else
                %li= link_to "Sign In with Github", user_omniauth_authorize_path(provider: :github)
              %li= link_to "Topics", topics_path
          / /.nav-collapse
    .container-fluid
      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Home", root_path
              %li= link_to "Topics", topics_path
          / /.well
        / /span
        .span9
          = bootstrap_flash
          = notice
          = alert
          = yield
      / /row
      %footer
        %p © Company 2014
    / /container

app/views/topics/_form.html.haml
= form_for @topic, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :student_id, :class => 'control-label'
    .controls
      = f.text_field :student_id, :class => 'text_field'
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .control-group
    = f.label :proposed_date, :class => 'control-label'
    .controls
      = f.text_field :proposed_date, :class => 'text_field'
  .control-group
    = f.label :completed_date, :class => 'control-label'
    .controls
      = f.text_field :completed_date, :class => 'text_field'
  .control-group
    = f.label :approved, :class => 'control-label'
    .controls
      = f.text_field :approved, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), topics_path, :class => 'btn'

app/views/topics/_topic_list.haml
- topics.each do |topic|
  %tr
    %td= get_student_name_for topic
    %td= link_to topic.title, topic_path(topic)
    %td= topic.description
    %td= topic.proposed_date
    %td= topic.completed_date
    %td
      - if topic.student == current_user
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_topic_path(topic), :class => 'btn btn-mini'
        = link_to t('.destroy', :default => t("helpers.links.destroy")), topic_path(topic), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/topics/edit.html.haml
- model_class = Topic
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/topics/index.html.haml
- model_class = Topic
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      - @headings.each do |h|
        %th= model_class.human_attribute_name(h)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - ["Approved Topics", "Pending Topics", "Completed Topics"].each do |list|
      %tr
        %th{colspan: @headings.size+1}= list
      = render "topic_list", topics: eval("@#{list.downcase.gsub(' ', '_')}")

= link_to t('.new', :default => t("helpers.links.new")), new_topic_path, :class => 'btn btn-primary'

app/views/topics/new.html.haml
- model_class = Topic
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/topics/show.html.haml
- model_class = Topic
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:student_id) + ':'
  %br
  = @topic.student_id
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @topic.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @topic.description
%p
  %strong= model_class.human_attribute_name(:proposed_date) + ':'
  %br
  = @topic.proposed_date
%p
  %strong= model_class.human_attribute_name(:completed_date) + ':'
  %br
  = @topic.completed_date
%p
  %strong= model_class.human_attribute_name(:approved) + ':'
  %br
  = @topic.approved

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), topics_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_topic_path(@topic), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), topic_path(@topic), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'